### ISSUE TITLE
Deprecated PageRequest constructors removed in Spring Boot 2.2

### ISSUE THREAD

**Issue by JanDoesJava** [Artur-/spring-data-provider#22]
The PageRequest constructors were deprecated and are now removed in Spring Boot 2.2.
Constructors should be replaced by PageRequest.of()

Traceback:
java.lang.IllegalAccessError: class org.vaadin.artur.spring.dataprovider.PageableDataProvider tried to access protected method org.springframework.data.domain.Sort.<init>(Ljava/util/List;)V (org.vaadin.artur.spring.dataprovider.PageableDataProvider and org.springframework.data.domain.Sort are in unnamed module of loader 'app')
	at org.vaadin.artur.spring.dataprovider.PageableDataProvider.createSpringSort(PageableDataProvider.java:53)
	at org.vaadin.artur.spring.dataprovider.PageableDataProvider.getPageable(PageableDataProvider.java:37)
	at org.vaadin.artur.spring.dataprovider.PageableDataProvider.fetchFromBackEnd(PageableDataProvider.java:25)
	at com.vaadin.flow.data.provider.AbstractBackEndDataProvider.fetch(AbstractBackEndDataProvider.java:61)
	at org.vaadin.artur.spring.dataprovider.FilterablePageableDataProvider.fetch(FilterablePageableDataProvider.java:28)

See https://stackoverflow.com/questions/44848653/pagerequest-constructors-have-been-deprecated

**Comment by bonifacechacha** [comment]
#21

**Comment by Artur-** [comment]
Fixed in #21 and 2.1.0
