### ISSUE TITLE
NoSuchMethodError with spring-data-jpa 2.0.0.RELEASE

### ISSUE THREAD

**Issue by pbaris** [Artur-/spring-data-provider#7]
With spring-data-jpa 2.0.0.RELEASE i get the following exception

`
12:27:10,752 SEVERE [com.vaadin.server.DefaultErrorHandler] (default task-12) : java.lang.NoSuchMethodError: org.springframework.data.domain.Pageable.getOffset()I
	at org.vaadin.artur.spring.dataprovider.PageableDataProvider.fromPageable(PageableDataProvider.java:91)
	at org.vaadin.artur.spring.dataprovider.PageableDataProvider.fetchFromBackEnd(PageableDataProvider.java:27)
	at com.vaadin.data.provider.AbstractBackEndDataProvider.fetch(AbstractBackEndDataProvider.java:61)
`

**Comment by bonifacechacha** [comment]
I am facing similar problem. I am using spring boot 2.0.1. Can you kindly assist?

**Comment by dominic-simplan** [comment]
same here...

**Comment by bonifacechacha** [comment]
I have submitted a pull request for the fix #9

**Comment by Artur-** [comment]
1.0.1 compiled using Vaadin 8.4 and Spring Data Commons 2.0.6.RELEASE. Hope this resolves the issue

**Comment by dominic-simplan** [comment]
@Artur- thanks!
